apiVersion: v1
kind: Namespace
metadata:
  name: qemu

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: multi-platform
  namespace: qemu
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: tonistiigi/binfmt
            name: multi-platform
            args:
            - '--install'
            - 'amd64'
            securityContext:
              privileged: true
          restartPolicy: Never
